# This file contains values from Cookiecutter

default_context:
  project_name: "xmldatafeed2gbq"
  project_description: "import from xmldatafeed.com to Google big query"
  organization: "ip ryzhov"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "Gamms"
  email: "ryjovm@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
